name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup rust
      run: npm run setup
    - name: trunk-action
      uses: jetli/trunk-action@v0.1.0
    - name: Build Frontend
      run: npm run frontend-prod
    - run: cd  ./backend
    - name: Build Backend
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
      
