name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup rust
      run: npm run setup
    - name: run rust tests
      run: cd ./frontend-ts/fountain && cargo test && cd ..
    - name: run js tests
      run: |
        cd ./frontend-ts
        npm install
        npm run test
    - name: Build Frontend
      run: cd ./frontend-ts && pnpm build
      
