name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run js tests
      run: |
        cd ./frontend-ts
        npm install
        npm run test
    - name: Build Frontend
      run: cd ./frontend-ts && npm run build -- --base=/script-collaboration-app/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: frontend-ts/dist
      
